dependencies:
  - python=3.7.1
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - tensorflow-gpu
  - keras
  - jupyter
  - requests
  - click
  - scipy
  - pip:
    - watermark
    - pytest
